# Generated by Django 2.1.2 on 2018-12-16 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='has_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='SpielerListe',
            field=models.ManyToManyField(related_name='player_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
