# Generated by Django 2.1.2 on 2018-12-17 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lobby', '0001_initial'),
        ('steam_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='lobby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Lobby.Lobby'),
        ),
    ]
